### ISSUE TITLE
Possible memory leak in Manager.h

### ISSUE THREAD

**Issue by brampedgex** [DisabledMallis/Nuvola#28]
https://github.com/DisabledMallis/Nuvola/blob/master/Nuvola/Client/Features/Manager.h#L9

It seems unnecessary to have a pointer to an std::vector, and I don't see anything freeing the memory when destroyed.

**Comment by DisabledMallis** [comment]
This should do the trick
https://github.com/DisabledMallis/Nuvola/blob/master/Nuvola/Client/Features/Manager.h#L15

**Comment by DisabledMallis** [comment]
Re open if not
